services:
  # --------------------------------
  # Lavalink (Audio node)
  # --------------------------------
  lavalink:
    # Only start if '--profile lavalink' is used
    # Useful if you want to use an external/hosted Lavalink node
    profiles: [lavalink, all]
    container_name: lavamusic-lavalink
    image: ghcr.io/lavalink-devs/lavalink:latest
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx2G # Limit memory usage to 2GB
      - SERVER_PORT=2333
    volumes:
      # Mount application.yml from the same directory or use environment variables
      - ./Lavalink/application.yml:/opt/Lavalink/application.yml
      # Persist plugins between restarts
      # Make sure to set the correct permissions (user: 322, group: 322)
      - ./Lavalink/plugins/:/opt/Lavalink/plugins/
    networks:
      - lavalink
    ports:
      - "2333:2333"
    healthcheck:
      test: 'curl -H "Authorization: youshallnotpass" -s http://localhost:2333/version'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  # -------------------------------
  # Postgres (Database)
  # -------------------------------
  postgres:
    # Only start if '--profile postgres' is used
    profiles: [postgres, all]
    container_name: lavamusic-postgres
    image: postgres:16-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: lavamusic
      POSTGRES_PASSWORD: lavamusic
      POSTGRES_DB: lavamusic
    volumes:
      - ./lavamusic-postgres:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U lavamusic"
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lavalink

  # --------------------------------
  # LavaMusic (Bot)
  # --------------------------------
  lavamusic:
    container_name: lavamusic
    image: ghcr.io/bongodevs/lavamusic:main
    restart: on-failure
    # Load environment variables from the local .env file
    env_file:
      - .env
    environment:
      # External/Hosted Lavalink (no profile needed):
      # - NODES=[{"id":"Hosted Node","host":"lava.example.com","port":80,"authorization":"youshallnotpass"}]
      # Local Lavalink node (requires '--profile lavalink'):
      # - NODES=[{"id":"Local Node","host":"lavalink","port":2333,"authorization":"youshallnotpass"}]

      # See docs/CONFIGURATION.md#database-configuration for supported formats
      # - SQLite: file:./lavamusic.db
      # - PGLite: file:./lavamusic-pgdata
      # - Postgres (requires '--profile postgres'): postgresql://lavamusic:lavamusic@postgres:5432/lavamusic
      - DATABASE_URL=file:./lavamusic-pgdata
    volumes:
      # Allow translation updates without rebuilding
      # - ./locales:/app/locales
      - ./lavamusic-pgdata:/app/lavamusic-pgdata
    depends_on:
      lavalink:
        condition: service_healthy
        required: false # Bot starts even if local lavalink is disabled
      postgres:
        condition: service_healthy
        required: false # Bot starts even if postgres is disabled
    networks:
      - lavalink

networks:
  lavalink:
    name: lavalink
